version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: wye-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wye.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    restart: unless-stopped
